version: '2'

services:
  redisearch_exporter:
    image: redisbench/redisearch_exporter:latest
    ports:
      - 9122:9122
    entrypoint: /redisearch_exporter -static-index-list "idx,idx1,pages-meta-idx1" -redis.addr redis://host.docker.internal:6379

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    entrypoint: /redis_exporter -redis.addr redis://host.docker.internal:6379

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - redisearch_exporter:redisearch_exporter
      - redis_exporter:redis_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      #      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - prometheus
    env_file:
      - 'env.grafana'
    user: "0"

#volumes:
#  grafana-storage: