global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: redis_exporter
    scrape_interval: 2s
    scrape_timeout: 1s
    static_configs:
      - targets:
          - redis_exporter:9121

  - job_name: redisearch_exporter
    scrape_interval: 2s
    scrape_timeout: 1s
    static_configs:
      - targets: ['redisearch_exporter:9122']
