# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-latest: # test with redisearch:latest
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:latest

    working_directory: /go/src/github.com/RediSearch/ftsb
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

  build-edge: # test nightly with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge

    working_directory: /go/src/github.com/RediSearch/ftsb
    steps:
      - checkout
      - run: make test

  ci-benchmark: # test nightly with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge

    working_directory: /go/src/github.com/RediSearch/ftsb
    steps:
      - checkout
      - run: make
      - run: sudo apt install python3.6 -y
      - run: sudo apt install python3-pip -y
      - run: python3 -m pip install redisbench-admin==0.1.6
      - run: |
             redisbench-admin run \
             --repetitions 7 \
             --output-file-prefix circleci \
             --upload-results-s3 \
             --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json

  build-multiarch-docker:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_REDISBENCH_PWD" | base64 --decode | docker login --username $DOCKER_REDISBENCH_USER --password-stdin
      - run:
          name: Build
          command: |
            make docker-release
          no_output_timeout: 20m

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-latest
      - ci-benchmark

  ci_benchmarks:
    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ci-benchmark
