version: 2.1

jobs:
  build-edge: # test with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-action/master/codecov) -t ${CODECOV_TOKEN}

  build-latest: # test with redisearch:latest
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:latest

    steps:
      - checkout
      - run: make test

workflows:
  commit:
    jobs:
      - build-latest
      - build-edge:
          requires:
            - build-latest
