version: 2.1

executors:
  edge:
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge
  latest:
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:latest

jobs:
  ci-benchmark:
    parameters:
      redisearch_version:
        type: executor
      use_case:
        type: string
    executor: << parameters.redisearch_version >>
    steps:
      - checkout
      - run: make
      - run: sudo apt install python3.6 -y
      - run: sudo apt install python3-pip -y
      - run: python3 -m pip install wheel redisbench-admin==0.1.11
      - run:
         name: << parameters.use_case >> use case
         command: |
           redisbench-admin run \
            --repetitions 3 \
            --output-file-prefix circleci \
            --upload-results-s3 \
            --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/<< parameters.use_case >>/<< parameters.use_case >>.redisearch.cfg.json

  build-edge: # test with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge
    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

  build-latest: # test with redisearch:latest
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:latest

    steps:
      - checkout
      - run: make test

workflows:
  commit:
    jobs:
      - build-edge
      - build-latest
      - ci-benchmark:
          matrix:
            parameters:
              redisearch_version: [edge]
              use_case: ["ecommerce-inventory","nyc_taxis-ft.add","nyc_taxis-hashes"]

  ci_benchmarks:
    triggers:
      - schedule:
          cron: "0 0,6,12,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ci-benchmark:
          matrix:
            parameters:
              redisearch_version: [edge]
              use_case: ["ecommerce-inventory","nyc_taxis-ft.add","nyc_taxis-hashes"]
