# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-edge: # test with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge

    steps:
      - checkout
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

  build-latest: # test with redisearch:latest
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:latest

    steps:
      - checkout
      - run: make test

  ci-benchmark-edge: # test nightly with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:edge

    steps:
      - checkout
      - run: make
      - run: sudo apt install python3.6 -y
      - run: sudo apt install python3-pip -y
      - run: python3 -m pip install wheel redisbench-admin==0.1.10
      - run:
          name: ecommerce-inventory use case
          command: |
            redisbench-admin run \
             --repetitions 7 \
             --output-file-prefix circleci \
             --upload-results-s3 \
             --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json
      - run:
          name: nyc_taxis CI use case with HSET
          command: |
            redisbench-admin run \
            --repetitions 3 \
            --output-file-prefix circleci \
            --benchmark-requests 1000000 \
            --upload-results-s3 \
            --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/nyc_taxis-hashes-CI/nyc_taxis-hashes-CI.redisearch.cfg.json
          no_output_timeout: 30m
      - run:
          name: nyc_taxis CI use case with FT.ADD
          command: |
            redisbench-admin run \
            --repetitions 3 \
            --output-file-prefix circleci \
            --benchmark-requests 1000000 \
            --upload-results-s3 \
            --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/nyc_taxis-ftadd-CI/nyc_taxis-ftadd-CI.redisearch.cfg.json
          no_output_timeout: 30m

  ci-benchmark-latest: # test nightly with redisearch:edge
    docker:
      - image: circleci/golang:1.13
      - image: redislabs/redisearch:latest

    steps:
      - checkout
      - run: make
      - run: sudo apt install python3.6 -y
      - run: sudo apt install python3-pip -y
      - run: python3 -m pip install wheel redisbench-admin==0.1.10
      - run: |
          redisbench-admin run \
          --repetitions 7 \
          --output-file-prefix circleci \
          --upload-results-s3 \
          --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json


  build-multiarch-docker:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_REDISBENCH_PWD" | base64 --decode | docker login --username $DOCKER_REDISBENCH_USER --password-stdin
      - run:
          name: Build
          command: |
            make docker-release
          no_output_timeout: 20m

workflows:
  version: 2
  commit:
    jobs:
      - build-edge
      - build-latest
      - ci-benchmark-edge
      - ci-benchmark-latest:
          requires:
            - ci-benchmark-edge

  ci_benchmarks:
    triggers:
      - schedule:
          cron: "0 0,6,12,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ci-benchmark-edge
      - ci-benchmark-latest:
          requires:
            - ci-benchmark-edge
