{
 "title": "RediSearch",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Redis Commands Processed Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_total{}[10s])",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes{} ", "legendFormat": "used" }
   ]
  },
  {
   "title": "Overall Redis CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(redis_cpu_user_seconds_total{}[10s])",
     "legendFormat": "CPU User"
    },
    {
     "expr": "irate(redis_cpu_sys_seconds_total{}[1m])",
     "legendFormat": "CPU Sys"
    }
   ]
  },
  {
   "title": "GC Total Time By Minute by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(redisearch_gc_stats_total_ms_run{}[1m])",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "Document Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Documents By Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "redisearch_num_docs",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Max Doc ID by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redisearch_max_doc_id",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Number of distinct terms by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redisearch_num_terms",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Number of records by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redisearch_num_records",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "GC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GC Total Time By Minute by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(redisearch_gc_stats_total_ms_run{}[1m])",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "GC Total Cycles by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redisearch_gc_stats_total_cycles",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "GC Last Run Time (ms) by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "redisearch_gc_stats_last_run_time_ms",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "GC Average Cycle Time (ms) by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "redisearch_gc_stats_avarage_cycle_time_ms",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "GC Blocks denied by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redisearch_gc_stats_gc_blocks_denied",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "GC numeric trees missed by Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redisearch_gc_stats_gc_numeric_trees_missed",
     "legendFormat": "Index - {{idx}} | Instance {{instance}}"
    }
   ]
  },
  {
   "title": "Inverted Index Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inverted Size in Bytes by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redisearch_inverted_size_bytes",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Total Inverted Index Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "redisearch_total_inverted_index_blocks",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "OffSet Vectors Size in Bytes by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redisearch_offset_vectors_size_bytes",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Doc Table Size in Bytes by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redisearch_doc_table_size_bytes",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Sortable Values Size in Bytes by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redisearch_sortable_values_size_bytes",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Key Table Size in Bytes by Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redisearch_sortable_values_size_bytes",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cursor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cursor Stats By Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redisearch_cursor_stats_index_total",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Cursor Stats By Index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redisearch_cursor_stats_index_total",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Cursor Global Total Idle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redisearch_cursor_stats_global_idle",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    },
    {
     "title": "Cursor Global Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redisearch_cursor_stats_global_total",
       "legendFormat": "Index - {{idx}} | Instance {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}