name: CI benchmark

on:
  push:
    branches: [ automation ]
  pull_request:
    branches: [ automation ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redislabs/redisearch:edge
        ports:
          - 6379:6379
    strategy:
      matrix:
        go: [ '1.14']
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOPATH
          export PATH=$PATH:$GOBIN
          mkdir -p $GOPATH/pkg
          mkdir -p $GOBIN
          mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
          mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
          cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
      - run: go get -v -u $GOPATH/src/github.com/$GITHUB_REPOSITORY/...
      - run: go test ./...
      - run: go install ./...

      - name: Get Python dependencies
        run: |
          sudo apt install python3.6 -y
          sudo apt install python3-pip -y
          sudo apt-get install python3-setuptools -y
          python3 -m pip install -r automation/requirements.txt

      - name: Run CI benchmarks
        run: |
          python3 ./automation/run.py \
               --repetitions 7 \
               --workers 1 \
               --output-file-prefix github-actions \
               --upload-results-s3 \
               --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json

