name: CI benchmark

on:
  push:
    branches: [ automation ]
  pull_request:
    branches: [ automation ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
    - uses: actions/checkout@v1
      with:
        go-version: 1.14.x
    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/12
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        make ftsb_redisearch

    - name: Get Python dependencies
      run: |
        sudo apt install python3.6 -y
        sudo apt install python3-pip -y
        sudo apt-get install python3-setuptools -y
        python3 -m pip install -r automation/requirements.txt

    - name: Run CI benchmarks
      run: |
        ./automation/run.py \
             --repetitions 7 \
             --output-file-prefix github-actions \
             --upload-results-s3 \
             --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json.
