name: CI benchmark

on:
  push:
    branches: [ automation ]
  pull_request:
    branches: [ automation ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Python dependencies
      run: |
        sudo apt install python3.6 -y
        sudo apt install python3-pip -y
        sudo apt-get install python3-setuptools -y
        python3 -m pip install -r automation/requirements.txt

    - name: Build
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        make

    - name: Run CI benchmarks
      run: |
      cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
      ./automation/run.py \
             --repetitions 7 \
             --output-file-prefix github-actions \
             --upload-results-s3 \
             --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json.
