name: CI benchmark

on:
  push:
    branches: [ automation ]
  pull_request:
    branches: [ automation ]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go get ./...

      - name: Get Python dependencies
        run: |
          sudo apt install python3.6 -y
          sudo apt install python3-pip -y
          sudo apt-get install python3-setuptools -y
          python3 -m pip install -r automation/requirements.txt

      - name: Run CI benchmarks
        run: |
          ./automation/run.py \
               --repetitions 7 \
               --output-file-prefix github-actions \
               --upload-results-s3 \
               --benchmark-config-file https://s3.amazonaws.com/benchmarks.redislabs/redisearch/datasets/ecommerce-inventory/ecommerce-inventory.redisearch.cfg.json.
