name: Integration Test

on:
  push:
    branches:
      - main
      - master
      - 'v*'
  pull_request:
    branches:
      - main
      - master
      - 'v*'
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run integration tests
        run: make integration-test
